#!/bin/bash
set -eo pipefail

if ! type shellcheck >/dev/null 2>&1; then
    echo -e "pre-commit-hook: missing \033[1;31mshellcheck\033[0m command"
    exit 1
fi

git ls-files --exclude='*.sh' --exclude="*.bash" --ignored | xargs shellcheck
shellcheck "$(git rev-parse --show-toplevel)/terrascript"