#!/bin/bash
set -eo pipefail

if [[ "$(type shellcheck >/dev/null 2>&1; echo $?)" -eq 1 ]]; then
    echo -e "\033[1;31mError\033[0m: missing shellcheck command"
    exit 1
fi

files=$(git diff --diff-filter=d --cached --name-only "$(git rev-parse --show-toplevel)"/terrascript)

if [ -n "$files" ]
then
    shellcheck "$(git rev-parse --show-toplevel)/terrascript"
    exit $?
fi