stages:
- build

variables:
  APP_NAME: ardikabs/terrascript
  APP_VERSION: ${CI_COMMIT_TAG}
  TERRAFORM_VERSION: 0.12.25

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "$DOCKERCONFIG" | base64 -d > /kaniko/.docker/config.json
    - executor
      --context $CI_PROJECT_DIR
      --dockerfile build/Dockerfile
      --destination ${APP_NAME}:${APP_VERSION}
      --build-arg=TERRAFORM_VERSION=${TERRAFORM_VERSION}
  when: manual
